### ISSUE TITLE
Where are the downloaded models stored?

### ISSUE THREAD

**Issue by geekjr** [UKPLab/EasyNMT#11]
Hello. Where are the downloaded models stored on a Mac?(I am talking about the large, 300MB models.

**Comment by nreimers** [comment]
They are stored in ~/.cache/torch/easynmt.

If you use the opus-mt models, the respective huggingface transformers model is stored ~/.cache/transformers (I something like that)

**Comment by geekjr** [comment]
Thanks. I was able to find them at those paths. Do you know by chance how to run those transformer models on iOS locally?

**Comment by nreimers** [comment]
You can just install Python, then install easynmt with pip and run the shown code.

**Comment by geekjr** [comment]
I have done that, and it works very well! However, I would like to use that model in an iOS mobile app using CoreML. Do you know how to do that?

**Comment by nreimers** [comment]
I never programmed for iOS. But this could help
https://pytorch.org/mobile/ios/

**Comment by geekjr** [comment]
Thank you. That helped. In your library, where do you load in the model?

**Comment by nreimers** [comment]
https://github.com/UKPLab/EasyNMT/blob/main/easynmt/models/OpusMT.py#L22

**Comment by geekjr** [comment]
Thank you very much! I will close this.
