### ISSUE TITLE
Can EasyNMT be used to train your own model using own dataset?

### ISSUE THREAD

**Issue by mzeidhassan** [UKPLab/EasyNMT#12]
First, thanks for this. It looks promising.

Can it be used to train your own model using your own training dataset? 

Thanks,

**Comment by nreimers** [comment]
Hi @mzeidhassan 
This is not yet implemented. But it will be added soon.

**Comment by mzeidhassan** [comment]
Thanks @nreimers ! This will be a great and much-needed addition to EasyNMT. Good luck and thanks for making this available.
