### ISSUE TITLE
Library not translating, just returning input

### ISSUE THREAD

**Issue by geekjr** [UKPLab/EasyNMT#14]
Hello
I am running the following code
```python
from easynmt import EasyNMT

model = EasyNMT('opus-mt')

print(model.translate("停", target_lang='en'))
```

The result of the code is just "停", which is the exact same thing as the input. How can i fix this?

**Comment by nreimers** [comment]
It can be that the language detection steps identifies the wrong language.

You can try and also pass the source_lang parameter to the translate method.

**Comment by geekjr** [comment]
That solved the problem!

**Comment by geekjr** [comment]
Is there any way to improve the auto detection?

**Comment by nreimers** [comment]
When you install these packages:

```
pip install langid langdetect
```

Then there are 3 language detection methods:
```
from easynmt import EasyNMT

model = EasyNMT('opus-mt')
t = "停"
print(model.language_detection_fasttext(t))
print(model.language_detection_langid(t))
print(model.language_detection_langdetect(t))
```

By default, fasttext is used.

You can change the method for the automatic language detection that is used for translation like this:
```
model._lang_detectors = [model.language_detection_langid]
print(model.language_detection(t))
```

Note:
language_detection_langdetect returns 'zh-cn' for the above example, however, the opus-mt model requires that the language code is 'zh' to work.

**Comment by geekjr** [comment]
Thank you. That worked.
