### ISSUE TITLE
how to use m2m_100 _12B Model??

### ISSUE THREAD

**Issue by im-yangp** [UKPLab/EasyNMT#15]
https://github.com/pytorch/fairseq/tree/master/examples/m2m_100

**Comment by nreimers** [comment]
The 12B model is currently not supported, as running it is quite complex (you need to split the model across multiple GPUs)

**Comment by im-yangp** [comment]
Do you know what configuration is required to run this model

**Comment by im-yangp** [comment]
Thank you
