### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by FrancoisMasson1990** [UKPLab/EasyNMT#21]
Hello I got the following error when using pytorch with GPU (the code works fine with using only CPU)
`RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)``
 when I run a simple basic example such as 
```
from easynmt import EasyNMT
model = EasyNMT('m2m_100_1.2B')
print(model.translate("Bonjour", target_lang='en'))
```
I have cuda 11.0 installed and a GPU 6Gb GeForce GTX 1660. 

Does anyone have encountered the same issue ?

**Comment by nreimers** [comment]
6GB might be a bit small, the model has already about 5GB. Then you need some more RAM for computation.

Can you try one of the other models (e.g. the opus-mt) models and see if it works?

**Comment by FrancoisMasson1990** [comment]
The other one works fine. Thanks for the clarification
