### ISSUE TITLE
No module named 'easynmt.models.OpusMT' in PyCharm

### ISSUE THREAD

**Issue by Lorddickenstein** [UKPLab/EasyNMT#23]
Hello, I'm running this simple code in pycharm
`from easynmt import EasyNMT
model = EasyNMT("opus-mt")

print(model.translate("Hi", target_lang="fr"))`

and it gives me this error

> Traceback (most recent call last):
  File "H:/Documents/Python/Random.py", line 2, in <module>
    model = EasyNMT("opus-mt")
  File "C:\Users\Jerz King\AppData\Local\Programs\Python\Python37\lib\site-packages\easynmt\EasyNMT.py", line 69, in __init__
    module_class = import_from_string(self.config['model_class'])
  File "C:\Users\Jerz King\AppData\Local\Programs\Python\Python37\lib\site-packages\easynmt\util.py", line 56, in import_from_string
    module = importlib.import_module(module_path)
  File "C:\Users\Jerz King\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'easynmt.models.OpusMT'

I had the same error addressed [here](https://github.com/UKPLab/EasyNMT/issues/3) when installing easynmt, and followed the steps, nothing happened... how do I fix this?

**Comment by Lorddickenstein** [comment]
Finally fixed it. I just set up a new conda environment and change the interpreter to the one conda uses, however I get this warning: 

> FutureWarning: `prepare_seq2seq_batch` is deprecated and will be removed in version 5 of 🤗 Transformers. Use the regular `__call__` method to prepare your inputs and the tokenizer under the `with_target_tokenizer` context manager to prepare your targets. See the documentation of your specific tokenizer for more details
>   warnings.warn(

is this something I have to be worried about?

**Comment by nreimers** [comment]
You can ignore that.

Great that it works now

**Comment by Lorddickenstein** [comment]
thank you so much. I think I should close this issue.

**Comment by shah5488** [comment]
> Finally fixed it. I just set up a new conda environment and change the interpreter to the one conda uses, however I get this warning:
> 
> > FutureWarning: `prepare_seq2seq_batch` is deprecated and will be removed in version 5 of 🤗 Transformers. Use the regular `__call__` method to prepare your inputs and the tokenizer under the `with_target_tokenizer` context manager to prepare your targets. See the documentation of your specific tokenizer for more details
> > warnings.warn(
> 
> is this something I have to be worried about

@Lorddickenstein how did you resolve it there is no solution mentioned I finding it really tough to get easynmt with python3.6 tried pip install EasyNMT==0.0.2 @nreimers pls help
