### ISSUE TITLE
translate_stream method does not yield all translations if number of input texts is not divisible without remainder by the chunk size

### ISSUE THREAD

**Issue by haukelicht** [UKPLab/EasyNMT#24]
Hi there,

thanks for providing this great package!

I have encountered an issue with the `translate_stream` method of the EasyNMT class: If the number of input texts ('n_texts') is *not* divisible by the `chunk_size` (i.e. without remainder), `translate_stream` only yields the first `(n_texts // chunk_size) * chunk_size` translations.

A minimal working example can be found here: https://colab.research.google.com/drive/1coVyCXc8jnPdHVcFHaVEsTfv1KfhGkvm?usp=sharing

**Comment by nreimers** [comment]
Thanks for reporting this issue.

I fixed it in the code and hope I will be able to soon release a new version on pip.

Until then, you can install it from sources to get the bugfix.

**Comment by haukelicht** [comment]
Great, thanks!
