### ISSUE TITLE
Offline mode impossible?

### ISSUE THREAD

**Issue by JohnWinner** [UKPLab/EasyNMT#27]
I have installed easynmt docker on Windows 7 using Docker Toolbox. I also mapped the /cache folder to my local drive so cached data remain persistent after reboot. I tested and it works fine, I can see hundreds of megabytes of data in the cache folder when I try to translate in a new language.

The problem is that after a reboot, using an already downloaded language set, there is always a pretty long delay after the first translation call. I disabled my network card to test and indeed something is still downloaded from the internet even with data/models already in cached folder.
What is downloaded?
Is it possible to run in 100% offline mode?

**Comment by nreimers** [comment]
By default, huggingface transformers expect an internet connection. But you can enable an offline mode:
https://huggingface.co/transformers/installation.html#offline-mode

So when you start the container like this:
docker run -p 24080:80 -v [set your cache folder here]:/cache -e TRANSFORMERS_OFFLINE=1 easynmt/api:2.0-cpu


It will work in offline mode

**Comment by JohnWinner** [comment]
Wow so simple, I love it! Thank you so much for your work!
