### ISSUE TITLE
AttributeError: 'float' object has no attribute 'split'

### ISSUE THREAD

**Issue by sriprad** [UKPLab/EasyNMT#34]
Hi Team,
I have a question. I am trying to translate a column which has blanks in between.  I am using EasyMT and its giving an error. won't it work if there is a blanks or missing in between the rows of a column?

Thanks 
Srinivas

**Comment by nreimers** [comment]
Hi @sriprad 
You must make sure  that all elements in your column are strings. The error shows that some cells are of type float, which does not work.
So replace these cells with an empty string ''

**Comment by sriprad** [comment]
Hi @nreimers ,
Thank you. But when i dtype it shows object. 
![image](https://user-images.githubusercontent.com/8103667/119110409-6ae55180-ba22-11eb-8a97-077802dfd31c.png)
Please let me know your thoughts

thanks

**Comment by nreimers** [comment]
It is better you convert your pandas dataframe to a list of sentences (strings) and pass this to the translate method

**Comment by sriprad** [comment]
df_samples['translated_text'] = model.translate(df_samples['Сообщение об ОС поступления'], source_lang='ru', target_lang='en')
this is what i am currently doing . Anything missing?

thanks
