### ISSUE TITLE
[docker] Is it possible to cancel the translation process if the client request is cancelled or times out?

### ISSUE THREAD

**Issue by AgrimPrasad** [UKPLab/EasyNMT#40]
Thanks again for this wonderful project. 

We have a use case as follows. Is it possible to achieve this with EasyNMT? We haven't found any way to cancel ongoing translation processes yet.

1. HTTP Client makes an HTTP request to the docker container
2. The translation process may take a very long time, depending on the size of the input.
3. HTTP Client times out or cancels the request and retries again.

For Case 3, is it possible to cancel the ongoing translation process + HTTP request in order to reclaim processor resources for the next request immediately?

**Comment by nreimers** [comment]
Hi @AgrimPrasad 
I sadly don't know if / how this could be implemented. Maybe you can check the fastAPI docs and see if they mention, if  cancellations from the client can be detected and if a long running process can be interrupted.

But in general I think it might not work perfect, e.g. when the client suddenly dies without closing the connection, the server has no way to know this except of a timeout.

Maybe another way would be to restrict the number of sentences that can be translated with one call? Then, a client that cancels the request would not be so bad.

**Comment by AgrimPrasad** [comment]
Thanks for the hints 👍 . 

I used the [sentences](https://pkg.go.dev/gopkg.in/neurosnap/sentences.v1) library to break up the source texts into batches of sentences before sending it to EasyNMT and it seems to be performing well so far.

Closing this issue.
