### ISSUE TITLE
HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/Helsinki-NLP/opus-mt-no-en

### ISSUE THREAD

**Issue by vishwas31** [UKPLab/EasyNMT#43]
This is the error coming as the model is not available in the repo.

**Comment by nreimers** [comment]
Hi 
there is sadly not available model from OPUS-MT for NO-EN. Hence the error

**Comment by vishwas31** [comment]
I understood that, but is there going to be any model for  that?

**Comment by nreimers** [comment]
You could ask here:
https://github.com/Helsinki-NLP/Opus-MT

If they have a model for NO-EN or which model they recommend.
