### ISSUE TITLE
auto detect source_lang not correct

### ISSUE THREAD

**Issue by js-lan** [UKPLab/EasyNMT#47]
in my case, some ‘zh’ strings are detected to 'wuu', 'yue', 'eo'....actually, they are all 'zh' strings.

**Comment by nreimers** [comment]
Language detection is based on fasttext lang detect. Sadly it is not really 100% reliable, but sadly cannot change it.

What you can do:
- Use a different language detection lib (https://github.com/UKPLab/EasyNMT/blob/5ea48f5fb68be9e4be4b8096800e32b8ad9a45df/easynmt/EasyNMT.py#L34), e.g. langid or langdetect
- Provide the source_lang parameter to the translate method, then the language is not tried to be detected automatically.
