### ISSUE TITLE
Docker Error - Booted as backend: False - Response: {'detail': 'Not Found'}

### ISSUE THREAD

**Issue by phamvietloi** [UKPLab/EasyNMT#49]
I follow the Docker Setup but it did not work. Tried on both Ubuntu, Windows Docker and both cpu and cuda version but the same error of Booted as backend: False - Response: {'detail': 'Not Found'}. 
![image](https://user-images.githubusercontent.com/43338839/132615126-6e46edca-1c1b-4470-89bb-94ad351caaa0.png)

**Comment by nreimers** [comment]
Did you try to access the / URL? It is not defined and returns 404, as expected.

you have to access the /translate path, i.e. 
http://localhost:24080/translate?target_lang=en&text=Hallo%20Welt

**Comment by phamvietloi** [comment]
oh, it's my fault. Thanks so much :)
