### ISSUE TITLE
Swap Transformations

### ISSUE THREAD

**Issue by shachardon** [UKPLab/EasyNMT#59]
Thank you for your great work! It's super useful!

I have a suggestion for improvement - 
Some transformations are working with a "swap" principle. For example, in GenderSwap, if we had "sister" in the original sentence then it would be transformed to 'brother" and vice versa.
There are scenarios when it's important to know what direction the transformation went, female to male or male to female. In my case for example, I want to compare the performances of my model on female/male sentences on inference time.
I really liked the way TenseTransformation works. You need to specify in the constructor what tense (past/present/future) you want to transform to.Maybe that could be applicable for other swap transformations?

Thanks again!

**Comment by nreimers** [comment]
Sadly I'm not really familiar how this can be implemented. I'm not to deep in NMT research.

**Comment by shachardon** [comment]
Thank you for the quick response. I mixed some things here with another repo by mistake... You can ignore it :) Thanks again, Your code helped me a lot!
