### ISSUE TITLE
arm devices

### ISSUE THREAD

**Issue by seekingdeep** [UKPLab/EasyNMT#9]
@nreimers 
can an OPUS-MT model be inferenced on an arm based device, such as a raspberry pi?

**Comment by nreimers** [comment]
Not sure. Is Pytorch available for it? Can Huggingface transformers be used on it? If yes, then it should be able to run there.

**Comment by seekingdeep** [comment]
pytorch can be compiled for arm devices easily, pytorch might be even preparing for arm since apple have a new arm chip.
though Huggingface transformers i will need to check for that.
Though :sunglasses: if the stars align, are you willing to consider arm support
